#ifndef NATURALITY_FEATURE_SETTINGS
#define NATURALITY_FEATURE_SETTINGS
const bool NATURALITY_STAR_PULSES = true;
const bool NATURALITY_END_PARALLAX = true;
const bool NATURALITY_FIRE_VARIATION = true;
const bool NATURALITY_PIXEL_GLINT_ENABLED = true;
const bool NATURALITY_EMISSIVE_LAVA = true;
#endif
